/**
 * Auto-generates drizzle/migrations.ts from the migration folders.
 * Run after `drizzle-kit generate` to keep the barrel file in sync.
 *
 * Wrangler's esbuild bundler handles .sql imports as text via the
 * `rules` config in wrangler.json.
 */
import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const DRIZZLE_DIR = join(import.meta.dirname!, "..", "drizzle");
const OUT_FILE = join(DRIZZLE_DIR, "migrations.ts");

const folders = readdirSync(DRIZZLE_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(DRIZZLE_DIR, d.name, "migration.sql")))
  .sort((a, b) => a.name.localeCompare(b.name));

if (folders.length === 0) {
  console.log("No migrations found.");
  process.exit(0);
}

const imports: string[] = [];
const entries: string[] = [];

for (let i = 0; i < folders.length; i++) {
  const folder = folders[i].name;
  const timestamp = folder.slice(0, 14); // YYYYMMDDHHMMSS
  imports.push(`import m${i} from "./${folder}/migration.sql";`);
  entries.push(`  "${timestamp}": m${i},`);
}

const output = `// Auto-generated by scripts/generate-migrations.ts — do not edit
${imports.join("\n")}

export default {
  migrations: {
${entries.join("\n")}
  },
};
`;

writeFileSync(OUT_FILE, output);
console.log(`Generated ${OUT_FILE} with ${folders.length} migration(s).`);
